version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: e-com-postgres
    environment:
      POSTGRES_USER: suke
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: ecom-postgres-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - spring-net

volumes:
  pgdata:

networks:
  spring-net:
